version: "3.8"
name: "minecraft-hr"
services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "100.113.25.38:25565:25565/tcp"
      - "100.113.25.38:24454:24454/udp"
      - "10.147.17.9:25565:25565/tcp"
      - "10.147.17.9:24454:24454/udp"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      DIFFICULTY: "hard"
      MAX_MEMORY: "8G"
      VIEW_DISTANCE: "15"
      ONLINE_MODE: "TRUE"

    depends_on:
      restore-backup:
        condition: service_completed_successfully
    volumes:
      - /mnt/one-t-ssd/minecraft/worlds/helproom/data:/data
  # "init" container for mc to restore the data volume when empty
  restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - /mnt/one-t-ssd/minecraft/worlds/helproom/data:/data
      # Must be same mount as backups service, but can be read-only
      - /mnt/one-t-ssd/minecraft/backups/worlds/helproom:/backups:ro
  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - /mnt/one-t-ssd/minecraft/worlds/helproom/data:/data:ro
      - /mnt/one-t-ssd/minecraft/backups/worlds/helproom:/backups
