name: "grocy"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    # volumes:
    #   - /mnt/one-t-ssd/grocy/config:/config
    ports:
      - 100.113.25.38:9283:80
    restart: unless-stopped
