# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."grocy" = {
    image = "lscr.io/linuxserver/grocy:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/New_York";
    };
    volumes = [ "/mnt/one-t-ssd/grocy/config:/config:rw" ];
    ports = [ "100.113.25.38:9283:80/tcp" ];
    log-driver = "journald";
    extraOptions = [ "--network-alias=grocy" "--network=grocy_default" ];
  };
  systemd.services."podman-grocy" = {
    serviceConfig = { Restart = lib.mkOverride 90 "always"; };
    after = [ "podman-network-grocy_default.service" ];
    requires = [ "podman-network-grocy_default.service" ];
    partOf = [ "podman-compose-grocy-root.target" ];
    wantedBy = [ "podman-compose-grocy-root.target" ];
  };

  # Networks
  systemd.services."podman-network-grocy_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f grocy_default";
    };
    script = ''
      podman network inspect grocy_default || podman network create grocy_default
    '';
    partOf = [ "podman-compose-grocy-root.target" ];
    wantedBy = [ "podman-compose-grocy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-grocy-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
